version: '3'

services:
  redis:
    image: "redis:latest"
    container_name: redis
    ports:
      - "6379:6379"

  app:
    build:
      context: .
    container_name: app
    command: ["gunicorn", "--bind", ":8080", "--worker-class", "eventlet", "-w", "1", "app:app"]
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_ENDPOINT_URL=redis:6379

